'''Autogenerated dummy lxu package enabling code completion in Python editors
 MODO Build #569521
'''

import attrdesc
import attributes
import chanmod
import command
import decodeID4
import lxID4
import meta
import object
import package
import select
import service
import utils
import vector
